

INSERT INTO `nwk6xo0kfxk2yh9v`.`EmptyBaskets` (`basket_name`, `description`, `price`, `quantity`, `image`, `createdAt`, `updatedAt`) VALUES ('Blue Bow Basket', 'Blue Bow', '10.00', '100', 'c/assets/images/empty_basket/Basket_Fronts/blue_bow_front.png', '0', '0');
INSERT INTO `nwk6xo0kfxk2yh9v`.`EmptyBaskets` (`basket_name`, `description`, `price`, `quantity`, `image`, `createdAt`, `updatedAt`) VALUES ('Brown Round Basket', 'Brown Round', '10.00', '100', 'c/assets/images/empty_basket/Basket_Fronts/brown_round_front.png', '0', '0');
INSERT INTO `nwk6xo0kfxk2yh9v`.`EmptyBaskets` (`basket_name`, `description`, `price`, `quantity`, `image`, `createdAt`, `updatedAt`) VALUES ('Brown with Straw', 'Brown with Straw', '10.00', '100', 'c/assets/images/empty_basket/Basket_Fronts/brown_with_straw_front.png', '0', '0');
INSERT INTO `nwk6xo0kfxk2yh9v`.`EmptyBaskets` (`basket_name`, `description`, `price`, `quantity`, `image`, `createdAt`, `updatedAt`) VALUES ('Flat Brown', 'Flat Brown', '10.00', '100', 'c/assets/images/empty_basket/Basket_Fronts/flat_brown_front.png', '0', '0');
INSERT INTO `nwk6xo0kfxk2yh9v`.`EmptyBaskets` (`basket_name`, `description`, `price`, `quantity`, `image`, `createdAt`, `updatedAt`) VALUES ('Red Bow', 'Red Bow', '10.00', '100', 'c/assets/images/empty_basket/Basket_Fronts/red_bow_front.png', '0', '0');
INSERT INTO `nwk6xo0kfxk2yh9v`.`EmptyBaskets` (`basket_name`, `description`, `price`, `quantity`, `image`, `createdAt`, `updatedAt`) VALUES ('Wide Tan', 'Wide Tan', '10.00', '100', 'c/assets/images/empty_basket/Basket_Fronts/wide_tan_front.png', '0', '0');
INSERT INTO `nwk6xo0kfxk2yh9v`.`EmptyBaskets` (`basket_name`, `description`, `price`, `quantity`, `image`, `createdAt`, `updatedAt`) VALUES ('Yellow Green', 'Yellow Green', '10.00', '100', 'c/assets/images/empty_basket/Basket_Fronts/yellow_green_front.png', '0', '0');
