
INSERT INTO `nwk6xo0kfxk2yh9v`.`Items` (`item_name`, `description`, `price`, `quantity`, `image`, `createdAt`, `updatedAt`) VALUES ('1950\'s Candy', 'Nostalgic Candy', '19.99', '100', '/public/assets/images/basket_item/PNG/1950_candy.png', '0', '0');
INSERT INTO `nwk6xo0kfxk2yh9v`.`Items` (`item_name`, `description`, `price`, `quantity`, `image`, `createdAt`, `updatedAt`) VALUES ('Apple-licious', 'Delicious Apple Treat', '4.99', '100', '/public/assets/images/basket_item/PNG/apple-licious.png', '0', '0');
INSERT INTO `nwk6xo0kfxk2yh9v`.`Items` (`item_name`, `description`, `price`, `quantity`, `image`, `createdAt`, `updatedAt`) VALUES ('Aunt Gloria Sugar Cookies', 'Better than yo Momma\'s', '4.99', '100', '/public/assets/images/basket_item/PNG/aunt_gloria_sugar_cookies.png', '0', '0');
INSERT INTO `nwk6xo0kfxk2yh9v`.`Items` (`item_name`, `description`, `price`, `quantity`, `image`, `createdAt`, `updatedAt`) VALUES ('Beer Brittle', 'Dig into these treasures', '5.99', '100', '/public/assets/images/basket_item/PNG/beer_brittle%20copy.png', '0', '0');
INSERT INTO `nwk6xo0kfxk2yh9v`.`Items` (`item_name`, `description`, `price`, `quantity`, `image`, `createdAt`, `updatedAt`) VALUES ('Birthday Wish Coffee Mug', 'Celebrate in style', '8.99', '100', '/public/assets/images/basket_item/PNG/birthday_wish_coffee_mug.png', '0', '0');
INSERT INTO `nwk6xo0kfxk2yh9v`.`Items` (`item_name`, `description`, `price`, `quantity`, `image`, `createdAt`, `updatedAt`) VALUES ('Cappacino', 'For the coffee lover looking for something else.', '9.99', '100', '/public/assets/images/basket_item/PNG/cappuccino_red.png', '0', '0');
INSERT INTO `nwk6xo0kfxk2yh9v`.`Items` (`item_name`, `description`, `price`, `quantity`, `image`, `createdAt`, `updatedAt`) VALUES ('Chocolate Chip Cookies', 'Better than Aunt Gloria\'s', '5.99', '100', '/public/assets/images/basket_item/PNG/chocolate_chip_cookies.png', '0', '0');
INSERT INTO `nwk6xo0kfxk2yh9v`.`Items` (`item_name`, `description`, `price`, `quantity`, `image`, `createdAt`, `updatedAt`) VALUES ('Coffee Candy', 'When your morning cup of Joe won\'t suffice', '9.75', '100', '/public/assets/images/basket_item/PNG/coffee_candy.png', '0', '0');
INSERT INTO `nwk6xo0kfxk2yh9v`.`Items` (`item_name`, `description`, `price`, `quantity`, `image`, `createdAt`, `updatedAt`) VALUES ('Fruit and Almond Snack', 'Delicious healthy snack', '6.50', '100', '/public/assets/images/basket_item/PNG/fruit_and_almond_snack.png', '0', '0');
INSERT INTO `nwk6xo0kfxk2yh9v`.`Items` (`item_name`, `description`, `price`, `quantity`, `image`, `createdAt`, `updatedAt`) VALUES ('Get Happy Tea', 'Rejuvenate your day', '5.25', '100', '/public/assets/images/basket_item/PNG/get_happy_tea.png', '0', '0');
INSERT INTO `nwk6xo0kfxk2yh9v`.`Items` (`item_name`, `description`, `price`, `quantity`, `image`, `createdAt`, `updatedAt`) VALUES ('Hibiscus Sangria Iced Tea', 'Refreshing iced tea', '5.25', '100', '/public/assets/images/basket_item/PNG/hibiscus_sangria_iced_tea.png', '0', '0');
INSERT INTO `nwk6xo0kfxk2yh9v`.`Items` (`item_name`, `description`, `price`, `quantity`, `image`, `createdAt`, `updatedAt`) VALUES ('Honey Mustard Dip', 'Liven up any snack', '5.25', '100', '/public/assets/images/basket_item/PNG/honey_mustard_dip.png', '0', '0');
INSERT INTO `nwk6xo0kfxk2yh9v`.`Items` (`item_name`, `description`, `price`, `quantity`, `image`, `createdAt`, `updatedAt`) VALUES ('Jelly Bean Popcorn', 'Tasty Jelly Beans flavored like real popcorn', '8.99', '100', '/public/assets/images/basket_item/PNG/jelly_belly_popcorn.png', '0', '0');
INSERT INTO `nwk6xo0kfxk2yh9v`.`Items` (`item_name`, `description`, `price`, `quantity`, `image`, `createdAt`, `updatedAt`) VALUES ('Krave Beef Jerky Chili Lime', 'Hot and Spicy Beef Jerky', '9.99', '100', '/public/assets/images/basket_item/PNG/krave_beef_jerky_chili_lime.png', '0', '0');
INSERT INTO `nwk6xo0kfxk2yh9v`.`Items` (`item_name`, `description`, `price`, `quantity`, `image`, `createdAt`, `updatedAt`) VALUES ('Krave Beef Jerky Sweet Chipotle', 'Sweet and Spicy beef jerky', '9.99', '100', '/public/assets/images/basket_item/PNG/krave_beef_jerky_chili_lime.png', '0', '0');
INSERT INTO `nwk6xo0kfxk2yh9v`.`Items` (`item_name`, `description`, `price`, `quantity`, `image`, `createdAt`, `updatedAt`) VALUES ('Lindt Gourmet Truffles', 'Enduldge in this delicacy', '19.99', '100', '/public/assets/images/basket_item/PNG/lindt_gourmet_truffles.png', '0', '0');
INSERT INTO `nwk6xo0kfxk2yh9v`.`Items` (`item_name`, `description`, `price`, `quantity`, `image`, `createdAt`, `updatedAt`) VALUES ('Pancake Waffle Mix', 'A delicious breakfast awaits', '9.75', '100', '/public/assets/images/basket_item/PNG/pancake_waffle_mix.png', '0', '0');
INSERT INTO `nwk6xo0kfxk2yh9v`.`Items` (`item_name`, `description`, `price`, `quantity`, `image`, `createdAt`, `updatedAt`) VALUES ('Peanuts in a burlap bag', 'Old school peanuts', '10.50', '100', '/public/assets/images/basket_item/PNG/peanuts_burlap_bag.png', '0', '0');
INSERT INTO `nwk6xo0kfxk2yh9v`.`Items` (`item_name`, `description`, `price`, `quantity`, `image`, `createdAt`, `updatedAt`) VALUES ('Peppermint Bark', 'A confectionary masterpiece', '8.75', '100', '/public/assets/images/basket_item/PNG/peppermint_bark.png', '0', '0');
INSERT INTO `nwk6xo0kfxk2yh9v`.`Items` (`item_name`, `description`, `price`, `quantity`, `image`, `createdAt`, `updatedAt`) VALUES ('Pistachios', 'Everyone\'s favorite nut', '14.99', '100', '/public/assets/images/basket_item/PNG/pistachio.png', '0', '0');
INSERT INTO `nwk6xo0kfxk2yh9v`.`Items` (`item_name`, `description`, `price`, `quantity`, `image`, `createdAt`, `updatedAt`) VALUES ('Sriracha Lime Pretzel Crisps', 'Spicy pretzel chips with a hint of lime', '4.99', '100', '/public/assets/images/basket_item/PNG/pretzel_crisps_sriracha_lime.png', '0', '0');
INSERT INTO `nwk6xo0kfxk2yh9v`.`Items` (`item_name`, `description`, `price`, `quantity`, `image`, `createdAt`, `updatedAt`) VALUES ('Chile Con Queso', 'Get your dip on', '5.99', '100', '/public/assets/images/basket_item/PNG/stonewall_chile_con_queso.png', '0', '0');
INSERT INTO `nwk6xo0kfxk2yh9v`.`Items` (`item_name`, `description`, `price`, `quantity`, `image`, `createdAt`, `updatedAt`) VALUES ('Summer Sausage', 'No gift basket is complete', '8.75', '100', '/public/assets/images/basket_item/PNG/summer_sausage.png', '0', '0');
INSERT INTO `nwk6xo0kfxk2yh9v`.`Items` (`item_name`, `description`, `price`, `quantity`, `image`, `createdAt`, `updatedAt`) VALUES ('Three Pepper Cracker', 'Nice bite to this cracker', '5.25', '100', '/public/assets/images/basket_item/PNG/three_pepper_cracker.png', '0', '0');

